window.levels = [
[
	"xxxxx",
	"xA..x",
	"x.x.x",
	"x.B.x",
	"xxxxx"
],
[
	"xxxxxxxxxxxxxxx",
	"xA.........xxxx",
	"xx.......xxxxxx",
	"xxxxx.....xxxxx",
	"xxxxx.....xxxxx",
	"xxxxx..x..xxxxx",
	"xxxxxxxx...xxxx",
	"x..xxxxx.x...xx",
	".............Bx",
	"xxxxxxxxxxxxxxx"
],
[
	"xxxxxxxxxxxxxxx",
	"xA............x",
	"x...iiifx.....x",
	"x..f..........x",
	"x.............x",
	"x.....i.......x",
	"x....f........x",
	"x.......ff....x",
	"x..........fffx",
	"x.............x",
	"x............Bx",
	"xxxxxxxxxxxxxxx",
]
];
